// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmXrsZuaANHzdh6pqN-uY6yhNcXBQapbg',
    appId: '1:576850851737:web:1f96c9cec019f6afdfc508',
    messagingSenderId: '576850851737',
    projectId: 'project-a319d61b-bdce-42c4-ae1',
    authDomain: 'project-a319d61b-bdce-42c4-ae1.firebaseapp.com',
    storageBucket: 'project-a319d61b-bdce-42c4-ae1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8qwFuwObJQdV_3OaFBcw2aTiINzMi-2c',
    appId: '1:576850851737:android:939c6836cb0d8a95dfc508',
    messagingSenderId: '576850851737',
    projectId: 'project-a319d61b-bdce-42c4-ae1',
    storageBucket: 'project-a319d61b-bdce-42c4-ae1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_jMwCraW3aXp2ZeIZg-_asU4mE3vVcZk',
    appId: '1:576850851737:ios:e915f10165f75a6ddfc508',
    messagingSenderId: '576850851737',
    projectId: 'project-a319d61b-bdce-42c4-ae1',
    storageBucket: 'project-a319d61b-bdce-42c4-ae1.firebasestorage.app',
    iosBundleId: 'com.example.safewalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_jMwCraW3aXp2ZeIZg-_asU4mE3vVcZk',
    appId: '1:576850851737:ios:e915f10165f75a6ddfc508',
    messagingSenderId: '576850851737',
    projectId: 'project-a319d61b-bdce-42c4-ae1',
    storageBucket: 'project-a319d61b-bdce-42c4-ae1.firebasestorage.app',
    iosBundleId: 'com.example.safewalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmXrsZuaANHzdh6pqN-uY6yhNcXBQapbg',
    appId: '1:576850851737:web:72af74938d3e64a7dfc508',
    messagingSenderId: '576850851737',
    projectId: 'project-a319d61b-bdce-42c4-ae1',
    authDomain: 'project-a319d61b-bdce-42c4-ae1.firebaseapp.com',
    storageBucket: 'project-a319d61b-bdce-42c4-ae1.firebasestorage.app',
  );
}
